<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Hom-Dev03" failures="1" tests="3" name="runner.RunSMSTest" time="90.343" errors="0" timestamp="2019-12-31T10:45:48 MST" skipped="0">
  <testcase classname="runner.RunSMSTest" name="runScenario" time="42.919">
    <failure message="expected [11] but found [12]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [11] but found [12]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at stepDefinitions.license.CEDCampaignGroup.user_exports_the_campaign_groups(CEDCampaignGroup.java:94)
at âœ½.User exports the campaign groups(src/test/resources/features/license/CEDCampaignGroup.feature:16)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.RunSMSTest" name="runScenario" time="22.224"/>
  <testcase classname="runner.RunSMSTest" name="runScenario" time="25.200"/>
</testsuite> <!-- runner.RunSMSTest -->
